AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cognito User Pool for TrackMyExpense authentication'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  SESEmailSourceArn:
    Type: String
    Default: ''
    Description: ARN of verified SES email (optional, leave empty to use Cognito default)

Conditions:
  UseSES: !Not [!Equals [!Ref SESEmailSourceArn, '']]

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'TrackMyExpense-Users-${Environment}'
      
      # Sign-in configuration
      UsernameAttributes:
        - email
      
      # Auto-verified attributes
      AutoVerifiedAttributes:
        - email
      
      # Password policy
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      
      # MFA configuration (optional)
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      
      # Account recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      
      # Email configuration
      EmailConfiguration:
        EmailSendingAccount: !If [UseSES, DEVELOPER, COGNITO_DEFAULT]
        SourceArn: !If [UseSES, !Ref SESEmailSourceArn, !Ref AWS::NoValue]
      
      # User attributes schema
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: updated_at
          AttributeDataType: Number
          Mutable: true
      
      # Email verification message
      EmailVerificationMessage: 'Welcome to TrackMyExpense! Your verification code is {####}'
      EmailVerificationSubject: 'Verify your TrackMyExpense account'
      
      # User pool add-ons
      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT
      
      # Tags
      UserPoolTags:
        Environment: !Ref Environment
        Application: TrackMyExpense
        ManagedBy: CloudFormation
  
  # User Pool Client (Web Application)
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'TrackMyExpense-Web-Client-${Environment}'
      UserPoolId: !Ref UserPool
      
      # Auth flows
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      
      # Token validity
      AccessTokenValidity: 1  # 1 hour
      IdTokenValidity: 1      # 1 hour
      RefreshTokenValidity: 30  # 30 days
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      
      # Prevent user existence errors
      PreventUserExistenceErrors: ENABLED
      
      # Read/Write attributes
      ReadAttributes:
        - email
        - name
        - email_verified
        - updated_at
      
      WriteAttributes:
        - email
        - name
        - updated_at
  
  # User Pool Domain (for hosted UI - optional)
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'trackmyexpense-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolArn:
    Description: ARN of the Cognito User Pool
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'
  
  UserPoolClientId:
    Description: ID of the User Pool Client
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  UserPoolDomain:
    Description: Domain for the User Pool
    Value: !Ref UserPoolDomain
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'
  
  UserPoolProviderURL:
    Description: Provider URL for the User Pool
    Value: !GetAtt UserPool.ProviderURL
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolProviderURL'
